-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admission
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nom text COLLATE pg_catalog."default",
    motif text COLLATE pg_catalog."default",
    diagnostique text COLLATE pg_catalog."default",
    date_admis text COLLATE pg_catalog."default",
    date_sortie text COLLATE pg_catalog."default",
    etat_sortie text COLLATE pg_catalog."default",
    medecin text COLLATE pg_catalog."default",
    infirmier text COLLATE pg_catalog."default",
    salle text COLLATE pg_catalog."default",
    lit text COLLATE pg_catalog."default",
    garde text COLLATE pg_catalog."default",
    CONSTRAINT admission_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.garde
(
    id bigint NOT NULL DEFAULT nextval('garde_id_seq'::regclass),
    nom text COLLATE pg_catalog."default",
    prenom text COLLATE pg_catalog."default",
    lien text COLLATE pg_catalog."default",
    adresse text COLLATE pg_catalog."default",
    tel text COLLATE pg_catalog."default",
    date_debut text COLLATE pg_catalog."default",
    date_fin text COLLATE pg_catalog."default",
    CONSTRAINT garde_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.infirmiere
(
    id bigint NOT NULL DEFAULT nextval('"Infirmiere_id_seq"'::regclass),
    nom text COLLATE pg_catalog."default",
    prenom text COLLATE pg_catalog."default",
    portable text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    photo bytea,
    CONSTRAINT "Infirmiere_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lit
(
    id bigint NOT NULL DEFAULT nextval('lit_id_seq'::regclass),
    numero text COLLATE pg_catalog."default",
    CONSTRAINT lit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medecin
(
    id integer NOT NULL,
    nom text COLLATE pg_catalog."default",
    specialite text COLLATE pg_catalog."default",
    tel text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    adresse text COLLATE pg_catalog."default",
    CONSTRAINT "Medecin_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id bigint NOT NULL DEFAULT nextval('notifications_id_seq'::regclass),
    message text COLLATE pg_catalog."default",
    lu boolean,
    date timestamp without time zone,
    nom text COLLATE pg_catalog."default",
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.patient
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nom text COLLATE pg_catalog."default",
    datenaiss text COLLATE pg_catalog."default",
    sexe text COLLATE pg_catalog."default",
    tel text COLLATE pg_catalog."default",
    cni text COLLATE pg_catalog."default",
    service text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    CONSTRAINT patient_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resultat
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nom text COLLATE pg_catalog."default",
    resultat_analyse text COLLATE pg_catalog."default",
    resultat_radio text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    tel text COLLATE pg_catalog."default",
    medecin text COLLATE pg_catalog."default",
    service text COLLATE pg_catalog."default",
    CONSTRAINT resultat_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.revisions
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nom text COLLATE pg_catalog."default",
    medicament text COLLATE pg_catalog."default",
    rendez text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    tel text COLLATE pg_catalog."default",
    medecin text COLLATE pg_catalog."default",
    service text COLLATE pg_catalog."default",
    CONSTRAINT revisions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.salle
(
    id bigint NOT NULL DEFAULT nextval('salle_id_seq'::regclass),
    numero text COLLATE pg_catalog."default",
    CONSTRAINT salle_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.service
(
    id bigint NOT NULL DEFAULT nextval('service_id_seq'::regclass),
    nom_service text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT service_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.soin
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nom text COLLATE pg_catalog."default",
    soin text COLLATE pg_catalog."default",
    salle text COLLATE pg_catalog."default",
    lit text COLLATE pg_catalog."default",
    infirmier text COLLATE pg_catalog."default",
    medecin text COLLATE pg_catalog."default",
    motif text COLLATE pg_catalog."default",
    CONSTRAINT "Soin_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    nom text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users1
(
    id bigint NOT NULL DEFAULT nextval('users1_id_seq'::regclass),
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    nom text COLLATE pg_catalog."default",
    CONSTRAINT users1_pkey PRIMARY KEY (id)
);
END;